data_opts:
  data_split_type: default
  test_image_set: test_NA
  fstride: 1
  min_track_size: 76
  sample_type: all
  seq_type: crossing
  subset: default
  test_seq_end: crossing_point
  train_seq_end: crossing_point
model_opts:
  apply_class_weights: true
  balance_data: true
  dataset: pie
  enlarge_ratio: 1.5
  fusion_method: sum
  fusion_point: early
  generator: true
  model: SFRNN
  normalize_boxes: true
  obs_input_type:
  - local_box
  - local_surround
  - pose
  - box
  - speed
  obs_length: 16
  overlap: 0.6
  time_to_event:
  - 30
  - 60
net_opts:
  backbone: vgg16
  cell_type: gru
  global_pooling: avg
  num_hidden_units: 256
  regularizer_val: 0.0001
train_opts:
  batch_size: 32
  epochs: 60
  learning_scheduler: null
  lr: 5.0e-05
